### PR TITLE
Week 1: updated portfolio

### PR DESCRIPTION
**Pull request by kevinkong03**

### CODE REVIEW

**Comment by rjkroege** [comment]
This branch contains everything in https://github.com/kevinkong03/software-product-sprint/pull/3 with a change. I have failed to explain the "best" workflow.

**Review by rjkroege — COMMENTED** [review]
These changes are good but you should rebase on `main` after finishing #3

**Comment by kevinkong03** [comment]
> These changes are good but you should rebase on `main` after finishing #3

What git command should I use to rebase... would it be like git pull origin updatedPortfolio --rebase?

**Comment by rjkroege** [comment]
How to rebase:

1. Click the "merge..." button in the Git UI
2. `git checkout main` in your local copy
3. `git pull` in your local copy. At this point, your local `main` branch should have the newly merged work from step 1
4. `git checkout <next branch>`
5. `git rebase main` to make the changes in `<next branch>` be w.r.t. to the new `main` head.

Read the `git-rebase` manual page. And/Or [this reasonable-looking webpage](https://www.becomebetterprogrammer.com/git-rebase/)

**Comment by kevinkong03** [comment]
> How to rebase:
> 
> 1. Click the "merge..." button in the Git UI
> 2. `git checkout main` in your local copy
> 3. `git pull` in your local copy. At this point, your local `main` branch should have the newly merged work from step 1
> 4. `git checkout <next branch>`
> 5. `git rebase main` to make the changes in `<next branch>` be w.r.t. to the new `main` head.
> 
> Read the `git-rebase` manual page. And/Or [this reasonable-looking webpage](https://www.becomebetterprogrammer.com/git-rebase/)

Sounds good, I've rebased on main after #3.

**Review by rjkroege — APPROVED** [review]

**Pull request merged**
